server:
  port: 8888

spring:
  application:
    name: mall-gateway
  cloud:
    loadbalancer:
      nacos:
        enabled: true
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        server-addr: ${spring.cloud.nacos.server-addr}
        group: online-mall
    sentinel:
      transport:
        dashboard: localhost:8089
    gateway:
      discovery:
        locator:
          enabled: false # 自动根据服务名生成路由
          lower-case-service-id: true # 服务名转小写
      routes:
        - id: user_service_route
          uri: lb://user-service # 这里是在 Nacos 上注册的服务名
          predicates:
            - Path=/user/**
        - id: order_service_route
          uri: lb://order-service
          predicates:
            - Path=/order/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    com.alibaba.cloud.nacos.discovery: DEBUG
    org.springframework.cloud.loadbalancer: DEBUG

#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"